# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jeremy Altman
title: Enterprise Systems Architect
email: jeremyaltman@outlook.com
website: jeremy.altmn.co

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: jeremyaltman
github_username:  jeremyaltman
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jeremyaltman
linkedin_username: altmanjeremy
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Multi-certified infrastructure architect/systems administrator with strong experience managing server infrastructures and data-center operations across Windows, macOS, Linux, and Unix platforms, both on-premise and in the clouds (Azure & AWS). Effectively plan, install, configure and optimize IT systems to achieve high availability and performance.

  Proven ability to create and deliver solutions tied to business growth, organizational development and systems/network optimization. Skilled problem identifier and troubleshooter comfortable managing systems, projects and teams in a range of IT environments.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Santanna Energy Services
        link: santannaenergyservices.com
        # link_text: santannaenergyservices.com
        sub_title: Infrastructure Architect
        caption: August 2018 - Present
        quote: >
          Rebuilt entire network infrastructure in a staged multi-project migration from layer-2 into the cloud.
        description: | # this will include new lines to allow paragraphs
            Migrated network from a single flat subnet to a multi-VLAN topology while migrating from Dell PowerConnect to Cisco Catalyst switches. Created Peplink SpeedFusion (SD-WAN) VPN tunnels to connect to various virtual networks within different Azure regions. Converted corporate wireless from WPA-PSK to WPA-Enterprise and replaced TP-Link with Aerohive WAPs.

            Created a new Active Directory Forest (functional level 2016) and migrated active user and computer objects from multiple legacy domains, utilizing organizational units and security groups.

            Implemented and executed a plan to migrate all mission critical servers and services into the Microsoft Azure cloud platform.

            Deployed Microsoft Azure Active Directory Connect (AD Connect) with modern authentication to consolidate user accounts and provide a single sign-on (SSO) environment.

            Converted the authorization and authentication mechanisms of various enterprise platforms to utilize Azure AD, On-Premise Active Directory, or LDAP for SSO with Role-Based Access Controls (RBAC).

            Migrated legacy file servers and mapped drives to OneDrive for Business/Office 365 Unified Group folders.

            Created a branded, standardized Windows 10 unified image and managed the upgrade of all workstations.

            Implemented BitLocker disk encryption to all workstations with recovery keys stored within Active Directory.

            Deployed Microsoft Local Administrator Password Solution (LAPS) to automatically create randomized, frequently updated passwords for local administrator accounts.

            Evaluated, recommended, and deployed Sophos Central with Intercept-X as endpoint protection to all workstations across the organization.

            Utilized containerization with Docker to consolidate Linux servers in Azure.

            Upgraded VMware ESXi/vSphere from 5.x to 6.7 and implemented Veeam Backup and Replication 9.5.

            Created an Active Directory user self-service portal with Adaxes along with the necessary automation, documentation, and training to allow the IT department to utilize Adaxes as a primary means of Active Directory administration.

            Initiated migration of legacy Shoretel-based phone system to cloud-based VOIP solution provided by 8x8 for the corporate and sales offices along with the 50-seat call center.

    content:
      - layout: left
        title: BPL Plasma
        link: bplplasma.com
        # link_text: bplplasma.com
        sub_title: Senior System Administrator
        caption: March 2016 - August 2018
        quote: >
          Managed information systems for 43 locations through organized and coordinated office procedures, operations, and resources. Research, design, implement, and troubleshoot information systems and technology solutions in support of business needs. Execute policy and procedural changes to develop and improve operational efficiency. Monitor for compliance of IT &amp; network policies. Plan and implement all IT-related projects, installations and modification. Oversee the continuous project development, system maintenance and improving the efficiency of Domain connected hardware and software.
        description: | # this will include new lines to allow paragraphs
            Performed scheduled maintenance, security updates, and routine monitoring of all servers across the enterprise
            Wrote Standard Operating Procedures (SOP) for the Information Technology department
            Secured wireless network by implementing WPA2 Enterprise encryption on AeroHive with Microsoft NPS
            Implemented and documented tiered data backup procedures and disaster recovery systems
            Established cross-platform domain integration and controls
            Ported traditional legacy PBX telephone systems across the enterprise to a single Voice Over IP system (Nextiva)
            Designed, deployed, managed and maintained AD DS/Active Directory, Directory Services (2,500+ users) across international enterprise network consisting of over 40 sites connected over NaaS and MPLS, created and maintained all group policies, and implemented role-based access control (RBAC) and delegation for management and security
            Managed Office 365 environment, including a large tenant to tenant migration and implemented Active Directory synchronization via Azure AD Connect with Single Sign-On
            Leveraged Windows Deployment Server (WDS) with customized images to install and deploy our validated operating system images and network boot various 3rd party diagnostic tools
            Utilized Windows Server Update Services (WSUS) to test, validate, and stage the installation of Windows and Microsoft Office Updates for local and remote sites
            Deployed cloud-based help desk ticketing system Samanage, including defining SLAs, maintaining change control, and asset/inventory management
            Deployed and configured Adaxes for management of Active Directory, along with AD Self-Service system for end-users to perform their own password resets/account unlocks, as well as Microsoft LAPS (Local Administrator Password Solution) to secure local administrative user accounts with constantly changing randomized passwords
            Extensively utilized PowerShell to automate complex AD and Office 365 management tasks
            Deployed VMware vSphere 6.5.0, including vMotion on 26 hosts with over 100 virtual machines backed up with Veeam Backup &amp; Replication
            Implemented Single Sign-On (SSO) Active Directory Identity Management with Centrify for various SAML-based cloud services including Samanage, Slack, Dropbox Enterprise, DocuSign, WebEx, ProLease, and OfficeSpace
            Additional notable systems deployed: LogMeIn Cloud, Sophos Central, SOTI MobiControl, OpenNMS

    content:
      - layout: left
        title: Crossroads Technology Group
        link: crosstg.com
        # link_text: crosstg.com
        sub_title: Senior Systems Engineer
        caption: April 2014 - January 2016
        quote: >
          Created and managed the technical side of Crossroads&#39; Managed Services division
        description: | # this will include new lines to allow paragraphs
            Designed, deployed, managed and maintained company network and data center
            Deployed Continuum Dashboard, SugarCRM, FreePBX/Asterisk VOIP, pfSense
            Setup &amp; maintained hosted Microsoft Exchange and Active Directory solutions
            Created &amp; monitored ShadowProtect Backup/Disaster Recovery systems
            Migrated customer networks to our VMware virtualized hosted environment
            Led team of technicians providing technical support to clients/end-users
            Upgraded office phone system from Toshiba Strata CIX40 to Asterisk/FreePBX VOIP

    content:
      - layout: left
        title: Syntek Systems
        link: synteksystems.net
        # link_text: synteksystems.net
        sub_title: Information Technology Consultant
        caption: March 2010 - March 2014
        quote: >
          Provided small business with customized technical solutions tailored to their needs
        description: | # this will include new lines to allow paragraphs
            Assisted clients with various break/fix issues and maintained monthly ongoing support contracts
            
            Developed custom tailored disaster recovery and backup solutions

    content:
      - layout: left
        title: Commodore USA
        link: commodoreusa.net
        # link_text: commodoreusa.net
        sub_title: Systems Engineer
        caption: April 2010 - March 2012
        quote: >
          Assisted in the design and development of the Commodore C64x, a retro-inspired PC
        description: | # this will include new lines to allow paragraphs
            Created the Linux system images that were pre-installed on all C64x and VIC Slim machines
            
            Managed and was responsible for backend network servers including production website and forums
            
            Assisted in production, assembly, quality control and shipping

    content:
      - layout: left
        title: Allied Kitchen &amp; Bath
        link: alliedkb.com
        # link_text: allliedkb.com
        sub_title: Information Technology Manager
        caption: July 2008 - March 2010
        quote: >
          Managed entire network and migrated email from local ISP to Windows 2003 Small Business Server/Exchange
        description: | # this will include new lines to allow paragraphs
            Planned and managed all company IT projects and team coordination/execution
            
            Installed 16-channel CCTV DVR Camera system with access control system
            
            Deployed NEC Elite IPK digital phone and voicemail system with dual T1 connections
            
            Provided desktop support for entire company

    content:
      - layout: left
        title: Interactive Intelligence
        link: inin.com
        # link_text: inin.com
        sub_title: Network Administrator
        caption: October 2000 - April 2005
        quote: >
          Responsible for managing the network and services for Interactive's Boca Raton Development Labs
        description: | # this will include new lines to allow paragraphs
            Managed complex wiring installation with over 600 CAT6 voice/data drops
            
            Maintained all equipment in server room/network operations &amp; development lab
            
            Deployed Cisco managed switches and routers, wireless access points, Shiva VPN gateways, multiple ISDN &amp; T1 lines, AMAG security system with personal access cards

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of South Florida
        caption: 1997 - 2000
        sub_title: Computer Science/Information Systems

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
